server:
  port: ${RIDE_SERVICE_PORT:8083}

spring:
  application:
    name: ride-management-service
  data:
    mongodb:
      uri: ${RIDE_DB_URI:mongodb+srv://ridelink_ride:ride123@cluster0.8j37ck1.mongodb.net/ride_db?retryWrites=true&w=majority&appName=Cluster0}

# Springdoc OpenAPI Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

# Interservice Communication Downstream Endpoints
services:
  account:
    url: ${ACCOUNT_SERVICE_URL:http://localhost:8081}
  driver:
    url: ${DRIVER_SERVICE_URL:http://localhost:8082}
  payment:
    url: ${PAYMENT_SERVICE_URL:http://localhost:8084}
